### ISSUE TITLE
FHazardRecord cannot access private member declared in class 'FHazardPointerCollection::FHazardRecord'

### ISSUE THREAD

**Issue by pkmital** [Conv-AI/Convai-UnrealEngine-SDK#14]
Hi, I am trying to compile the latest and running into a compile error:

```
Downloading...
From (original): https://drive.google.com/uc?id=1-sWOJ8amM425eoZDhnZ_1FEVdhXajI7L
From (redirected): https://drive.google.com/uc?id=1-sWOJ8amM425eoZDhnZ_1FEVdhXajI7L&confirm=t&uuid=0a28ecb6-51c2-4a5d-b1c8-1d19638a4a08
To: C:\dev\unreal\plugins\Convai-UnrealEngine-SDK.zip
100%|███████████████████████████████████████████████| 285M/285M [00:05<00:00, 48.2MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1qqrJXv62dz9MOsL9fMbL-E_RT5DhwB97
From (redirected): https://drive.google.com/uc?id=1qqrJXv62dz9MOsL9fMbL-E_RT5DhwB97&confirm=t&uuid=f4b7b267-ee5c-4a1a-bc70-f3d5fcee2730
To: C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Source.zip
100%|███████████████████████████████████████████████| 207M/207M [00:03<00:00, 56.5MB/s]
Building Plugin: C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\ConvAI.uplugin
"C:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin -Plugin="C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\ConvAI.uplugin" -Package="C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK" -Rocket -Marketplace -TargetPlatforms=Win64
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -Plugin=C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\ConvAI.uplugin -Package=C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK -Rocket -Marketplace -TargetPlatforms=Win64
Initializing script modules...
Total script module initialization time: 0.12 s.
Executing commands...
Copying 7670 file(s) using max 64 thread(s)
Reading plugin from C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\ConvAI.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\HostProject.uproject" -plugin="C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\ConvAI.uplugin" -noubtmakefiles -manifest="C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\pkmit\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\pkmit\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs(26,13): warning CS0436: The type 'ConvaiPlatform' in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs' conflicts with the imported type 'ConvaiPlatform' in 'HostProjectModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs'.
C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs(144,35): warning CS0436: The type 'ConvaiPlatform' in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs' conflicts with the imported type 'ConvaiPlatform' in 'HostProjectModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs'.
C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs(14,20): warning CS0436: The type 'ConvaiPlatform' in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs' conflicts with the imported type 'ConvaiPlatform' in 'HostProjectModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs'.
C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs(136,39): warning CS0436: The type 'ConvaiPlatform' in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs' conflicts with the imported type 'ConvaiPlatform' in 'HostProjectModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs'.
C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs(128,37): warning CS0436: The type 'ConvaiPlatform' in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs' conflicts with the imported type 'ConvaiPlatform' in 'HostProjectModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs'.
C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs(34,80): warning CS0436: The type 'ConvaiPlatform' in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs' conflicts with the imported type 'ConvaiPlatform' in 'HostProjectModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Plugins\ConvAI\Source\Convai\Convai.Build.cs'.
Parsing headers for UnrealEditor
  Running Internal UnrealHeaderTool C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\HostProject.uproject C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Intermediate\Build\Win64\UnrealEditor\Development\UnrealEditor.uhtmanifest -WarningsAsErrors -installed
Total of 38 written
Reflection code generated for UnrealEditor in 0.5685243 seconds
Writing manifest to C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Output\Convai-UnrealEngine-SDK\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml
Building UnrealEditor...
Using Visual Studio 2022 14.39.33519 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Determining max actions to execute in parallel (24 physical cores, 32 logical cores)
  Executing up to 24 processes, one per physical core
------ Building 12 action(s) started ------
[1/12] Resource Default.rc2
[2/12] Compile [x64] SharedPCH.Engine.Cpp20.cpp
C:\Program Files\Epic Games\UE_5.3\Engine\Source\predefined C++ types (compiler internal)(420): error C2248: 'FHazardPointerCollection::FHazardRecord::FHazardRecord': cannot access private member declared in class 'FHazardPointerCollection::FHazardRecord'
C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(86): note: see declaration of 'FHazardPointerCollection::FHazardRecord::FHazardRecord'
C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(77): note: see declaration of 'FHazardPointerCollection::FHazardRecord'
C:\Program Files\Epic Games\UE_5.3\Engine\Source\predefined C++ types (compiler internal)(420): note: the template instantiation context (the oldest one first) is
C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(133): note: see reference to function template instantiation 'void __builtin_array_init_helper<FHazardPointerCollection::FHazardRecord>(_T *,size_t) noexcept(<expr>)' being compiled
        with
        [
            _T=FHazardPointerCollection::FHazardRecord
        ]
Total time in Parallel executor: 8.09 seconds
Total execution time: 11.40 seconds
Took 11.46s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\pkmit\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 0m 13s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
Traceback (most recent call last):
  File "C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Build.py", line 137, in <module>
    main(ue_directory, repo_directory, extra_flags)
  File "C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Build.py", line 107, in main
    build_plugin(ue_directory, repo_directory, output_directory, extra_flags)
  File "C:\dev\unreal\plugins\Convai-UnrealEngine-SDK\Build.py", line 78, in build_plugin
    raise Exception("An error occurred during the build process")
Exception: An error occurred during the build process
```

Running on windows 11 w/ python 3.10

Any ideas very appreciated!

**Comment by GENL** [comment]
Same issue here.

**Comment by MohamedEshmawy** [comment]
Hi it seems as an issue with Visual Studio, try checking out the forum [here](https://forums.unrealengine.com/t/failure-to-create-a-new-project-cannot-access-private-member-declared-in-class-fhazardpointercollection-fhazardrecord/1548295)
