### ISSUE TITLE
An item with the same key has already been added. Key: ConvAI

### ISSUE THREAD

**Issue by ash1ey** [Conv-AI/Convai-UnrealEngine-SDK#5]
Since updating to 2.4 my android project started thowing up a duplicate key issue:

```
LogPlayLevel: Error: UAT: ERROR: System.ArgumentException: An item with the same key has already been added. Key: ConvAI
LogPlayLevel: UAT:           at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
LogPlayLevel: UAT:           at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
LogPlayLevel: UAT:           at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
LogPlayLevel: UAT:           at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
LogPlayLevel: UAT:           at AutomationTool.ProjectUtils.RequiresTempTarget(FileReference RawProjectPath, Boolean bProjectHasCode, UnrealTargetPlatform Platform, UnrealTargetConfiguration Configuration, TargetType TargetType, Boolean bRequiresAssetNativization, Boolean bRequiresCookedData, String& OutReason) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectUtils.cs:line 294
LogPlayLevel: UAT:           at AutomationTool.ProjectUtils.RequiresTempTarget(FileReference RawProjectPath, List`1 Platforms, List`1 Configurations, Boolean AssetNativizationRequested) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectUtils.cs:line 241
LogPlayLevel: UAT:           at AutomationTool.ProjectUtils.DetectProjectProperties(FileReference RawProjectPath, List`1 ClientTargetPlatforms, List`1 ClientTargetConfigurations, Boolean AssetNativizationRequested) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectUtils.cs:line 613
LogPlayLevel: UAT:           at AutomationTool.ProjectUtils.GetProjectProperties(FileReference RawProjectPath, List`1 ClientTargetPlatforms, List`1 ClientTargetConfigurations, Boolean AssetNativizationRequested) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectUtils.cs:line 175
LogPlayLevel: UAT:           at AutomationTool.ProjectParams.AutodetectSettings(Boolean bReset) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectParams.cs:line 2306
LogPlayLevel: UAT:           at AutomationTool.ProjectParams..ctor(FileReference RawProjectPath, BuildCommand Command, String Device, String MapToRun, String AdditionalServerMapParams, ParamList`1 Port, String RunCommandline, String StageCommandline, String BundleName, String StageDirectoryParam, String UnrealExe, String UE4Exe, String SignPak, List`1 ClientConfigsToBuild, List`1 ServerConfigsToBuild, ParamList`1 MapsToCook, ParamList`1 MapIniSectionsToCook, ParamList`1 DirectoriesToCook, String DDCGraph, String InternationalizationPreset, ParamList`1 CulturesToCook, ParamList`1 ClientCookedTa
rgets, ParamList`1 EditorTargets, ParamList`1 ServerCookedTargets, List`1 ClientTargetPlatforms, Dictionary`2 ClientDependentPlatformMap, List`1 ServerTargetPlatforms, Dictionary`2 ServerDependentPlatformMap, Nullable`1 Build, Nullable`1 SkipBuildClient, Nullable`1 SkipBuildEditor, Nullable`1 Cook, Nullable`1 Run, Nullable`1 SkipServer, Nullable`1 Clean, Nullable`1 Compressed, Nullable`1 ForceUncompressed, String AdditionalPakOptions, String AdditionalIoStoreOptions, Nullable`1 IterativeCooking, String IterateSharedCookedBuild, Nullable`1 IterateSharedBuildUsePrecompiledExe, Nullable`1 CookAll
, Nullable`1 CookPartialGC, Nullable`1 CookInEditor, String CookOutputDir, Nullable`1 CookMapsOnly, Nullable`1 CookOnTheFly, Nullable`1 CookOnTheFlyStreaming, Nullable`1 UnversionedCookedContent, Nullable`1 OptionalContent, Nullable`1 EncryptIniFiles, Nullable`1 EncryptPakIndex, Nullable`1 EncryptEverything, Nullable`1 SkipCookingEditorContent, String AdditionalCookerOptions, String OriginalReleaseVersion, String BasedOnReleaseVersion, String CreateReleaseVersion, String CreateReleaseVersionBasePath, String BasedOnReleaseVersionBasePath, String ReferenceContainerGlobalFileName, String Referenc
eContainerCryptoKeys, Nullable`1 GeneratePatch, Nullable`1 AddPatchLevel, Nullable`1 StageBaseReleasePaks, String DiscVersion, String DLCName, String DLCOverrideCookedSubDir, String DLCOverrideStagedSubDir, String DiffCookedContentPath, Nullable`1 DLCIncludeEngineContent, Nullable`1 DLCPakPluginFile, Nullable`1 DLCActLikePatch, Nullable`1 CrashReporter, Nullable`1 DedicatedServer, Nullable`1 Client, Nullable`1 Deploy, String DeployFolder, String GetFile, Nullable`1 FileServer, Nullable`1 Foreign, Nullable`1 ForeignCode, Nullable`1 LogWindow, Nullable`1 NoCleanStage, Nullable`1 NoClient, Nullab
le`1 NoDebugInfo, Nullable`1 SeparateDebugInfo, Nullable`1 MapFile, Nullable`1 NoXGE, Nullable`1 SkipPackage, Nullable`1 NeverPackage, Nullable`1 Package, Nullable`1 Pak, Nullable`1 IgnorePaksFromDifferentCookSource, Nullable`1 IoStore, Nullable`1 Cook4IoStore, Nullable`1 ZenStore, String NoZenAutoLaunch, Nullable`1 SkipIoStore, Nullable`1 GenerateOptimizationData, Nullable`1 Prereqs, String AppLocalDirectory, Nullable`1 NoBootstrapExe, Nullable`1 SignedPak, Nullable`1 PakAlignForMemoryMapping, Nullable`1 RehydrateAssets, Nullable`1 NullRHI, Nullable`1 FakeClient, Nullable`1 EditorTest, Nullab
le`1 RunAutomationTests, String RunAutomationTest, Nullable`1 CrashIndex, Nullable`1 SkipCook, Nullable`1 SkipCookOnTheFly, Nullable`1 SkipPak, Nullable`1 PrePak, Nullable`1 SkipStage, Nullable`1 Stage, Nullable`1 Manifests, Nullable`1 CreateChunkInstall, Nullable`1 SkipEncryption, Nullable`1 Unattended, Nullable`1 NumClients, Nullable`1 Archive, String ArchiveDirectoryParam, Nullable`1 ArchiveMetaData, Nullable`1 CreateAppBundle, String SpecifiedClientTarget, String SpecifiedServerTarget, ParamList`1 ProgramTargets, Nullable`1 Distribution, String PackageEncryptionKeyFile, Nullable`1 Prebuilt
, Nullable`1 RunTimeoutSeconds, String SpecifiedArchitecture, String UbtArgs, String AdditionalPackageOptions, Nullable`1 IterativeDeploy, Nullable`1 FastCook, Nullable`1 IgnoreCookErrors, Nullable`1 CodeSign, Nullable`1 TreatNonShippingBinariesAsDebugFiles, Nullable`1 UseExtraFlavor, String Provision, String Certificate, String Team, Boolean AutomaticSigning, String Trace, String TraceHost, String TraceFile, String SessionLabel, ParamList`1 InMapsToRebuildLightMaps, ParamList`1 InMapsToRebuildHLOD, ParamList`1 TitleID) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Automat
ionTool\AutomationUtils\ProjectParams.cs:line 1223
LogPlayLevel: UAT:           at BuildCookRun.SetupParams() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 49
LogPlayLevel: UAT:           at BuildCookRun.ExecuteBuild() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 40
LogPlayLevel: UAT:           at AutomationTool.BuildCommand.Execute() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 344
LogPlayLevel: UAT:           at AutomationTool.BuildCommand.ExecuteAsync() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 353
LogPlayLevel: UAT:           at AutomationTool.Automation.ExecuteAsync(List`1 CommandsToExecute, Dictionary`2 Commands) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 257
LogPlayLevel: UAT:           at AutomationTool.Automation.ProcessAsync(ParsedCommandLine AutomationToolCommandLine, StartupTraceListener StartupListener, HashSet`1 ScriptModuleAssemblies) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 156
LogPlayLevel: UAT:        (see C:\Users\gunne\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+Epic+Games+UE_5.1\Log.txt for full exception trace)
LogPlayLevel: UAT: AutomationTool executed for 0h 0m 0s
LogPlayLevel: UAT: AutomationTool exiting with ExitCode=1 (Error_Unknown)
LogPlayLevel: Completed Launch On Stage: Launch Task, Time: 1.271692
LogPlayLevel: UAT: BUILD FAILED
```

**Comment by MohamedEshmawy** [comment]
Looks like the Convai plugin was installed more than once on your system. To fix this, you just need to check three places:

- The plugins folder in your project folder.
- The plugins folder in the engine directory. For Windows, it's usually at Program Files/Epic Games/[ENGINE_NUMBER]/Engine/Plugins.
- If you installed it from the marketplace, open up the Epic launcher, click on Unreal Engine on the left and open the Library tab. Find the UE version you're using, click on Installed Plugins underneath, and a window will pop up. You should see Convai in there and can remove it.

You need to keep only one version of the plugin, so you need to remove two of these places, I would recommend leaving the Epic launcher plugin that you installed from the marketplace and deleting the others.

Hope this helps.
